print("╔═════════════════════╗")
print("║     ÇİZİMLER        ║") 
print("╠═════════════════════╣")
print("║  1-Kare çiz         ║")
print("║  2-Üçgen çiz        ║")
print("║  3-Desen çizimi     ║")
print("║  4-                 ║")
print("║  5-                 ║")
print("║  6-                 ║")
print("║  7-                 ║")
print("║  8-Anamenu          ║")
print("║  9-Çıkış            ║")
print("║                     ║")
print("║    Seçimiz nedir?   ║")
print("╚═════════════════════╝")
secim=input()
if secim=="1": import moduller.cizim_kare
if secim=="2": import moduller.cizim_ucgen
if secim=="9": exit()
